[package]
name = "ascii-pixel"
version = "1.0.0"
edition = "2021"
description = "Convert pixel art into ascii images"
license = "CC0"

[dependencies]
clap = { version = "4.5.16", features = ["cargo"] }
image = "0.25.2"
